In [40]:
import json
import os

# Data Preprocessing

In [161]:
import os
import json

class DataPreprocessor:
    def __init__(self):
        pass

    def preprocess(self,dataset):
        if dataset == 'friends':
            #self.friends(dataset)
            try:                
                self.friends(dataset)
                print("Friends data Processed Successfully :)")
            except Exception:
                print("Processing Failed:",str(Exception))
                
        elif dataset == 'bookscorpus':
            try:                
                booksCorpus(dataset)
                print("BoxCorpus data Processed Successfully :)")
            except Exception:
                print("Processing Failed:",Exception)

        elif dataset == 'movie_dialogues':
            self.movies(dataset)
            try:                
                self.movies(dataset)
                print("Movie Dialogues data Processed Successfully :)")
            except Exception:
                print("Processing Failed:",Exception)
    
    def friends(self,dataset):
        NO_OF_SEASONS = 11
        for i in range(1,NO_OF_SEASONS):
            file = open(os.path.join(os.getcwd(),'Datasets/raw_data/friends/friends_season_%.2d.json'%i))
            jtxt = json.load(file)
            dialogueList = []
            path = os.path.join(os.getcwd(),'Datasets/processed_data/friends/')    
            if not os.path.isdir(path):
                os.makedirs(path)
            tfile = open( os.path.join(path,"season%d.txt"%i), 'a+')
            for e in jtxt['episodes']:
                for scene in e['scenes']:
                    for utter in scene['utterances']:
                        speakers = ' '.join(utter['speakers'])+':\n'
                        dialogue = utter['transcript']+'\n\n'
                        if len(utter['speakers'])>0:
                            tfile.write(speakers)
                            tfile.write(dialogue)                
                            dialogueList.append(utter['transcript'])
            tfile.close()
            tfile = open( os.path.join(path,"season%d.txt"%i), 'r')
            # writes season(s) to one series file
            friends = open( os.path.join(path,"friends.txt"), 'a+')
            friends.write(tfile.read())
            friends.close()
            tfile.close()
            
    def movies(self,dataset):
        #NO_OF_SEASONS = 11
        path = os.path.join(os.getcwd(),'Datasets/processed_data/movies/')
        file = open(os.path.join(os.getcwd(),'Datasets/raw_data/movies/movie_lines.txt'),'rb').readlines()

        if not os.path.isdir(path):
            os.makedirs(path)
        tfile = open( os.path.join(path,"movie_dialogues.txt"), 'a+')
        for line in file:
            dialogue=""
            try:
                dialogue = line.decode('utf-8').split("+++$+++")[-1]
            except Exception as e:
                print("Error Here: ",line)
                print(e)
                break
            newText = dialogue.replace("\\n\'","")
            tfile.write(newText.rstrip('\n'))
    
        tfile.close()

In [162]:
dp = DataPreprocessor()
#dp.preprocess('friends')
dp.preprocess('movie_dialogues')

Error Here:  b'L19462 +++$+++ u198 +++$+++ m13 +++$+++ ELAINE +++$+++ You got a telegram from head\xadquarters today.\n'
'utf-8' codec can't decode byte 0xad in position 83: invalid start byte
Error Here:  b'L19462 +++$+++ u198 +++$+++ m13 +++$+++ ELAINE +++$+++ You got a telegram from head\xadquarters today.\n'
'utf-8' codec can't decode byte 0xad in position 83: invalid start byte
Movie Dialogues data Processed Successfully :)


In [127]:
path = os.path.join(os.getcwd(),'Datasets/processed_data/movies/')
tfile = open( os.path.join(path,"movie_dialogues.txt"), 'a+')
tfile.write(tfile.read().encode('utf-8').replace('\n\'',"").replace('\n\"',"").replace("\n",""))
tfile.close()

TypeError: a bytes-like object is required, not 'str'

In [131]:
file = open(os.path.join(os.getcwd(),'Datasets/raw_data/movies/movie_lines.txt'),'rb').readlines()
path = os.path.join(os.getcwd(),'Datasets/processed_data/movies/')
tfile = open( os.path.join(path,"movie_dialogues.txt"), 'a+')
tfile.write(for i in file.encode('ascii').replace('\n\'',"").replace('\n\"',"").replace("\n",""))
tfile.close()

SyntaxError: invalid syntax (4220911807.py, line 4)

In [121]:
"They do not!\n'".replace('\n\'',"").replace('\n\"',"").replace("\n","")

TypeError: replace() argument 1 must be str, not list

In [87]:
'a string'.encode('ascii').decode('ascii')

'a string'

In [2]:
import tiktoken
import time
import torch

In [3]:
# Loading cl100k_base encoder from tiktoken library
enc = tiktoken.get_encoding("cl100k_base")
# reading season1.txt file, which consists conversations from season 1 of friends
s1data = open('Datasets/processed_data/friends/friends.txt').read()
# encoding the entire season 1 data using cl100k_base encoder from OpenAI
tokens = enc.encode(s1data)

In [4]:
enc.encode(" ")

[220]

In [5]:
enc.decode([0])

'!'

In [6]:
print("Tokens Length: ",len(tokens),end='\n\n')
print("First 20 Encoded Tokens: ", tokens[:20],end='\n\n')
print("First 20 Decoded Tokens: ", enc.decode(tokens[:20]))

Tokens Length:  1152879

First 20 Encoded Tokens:  [11342, 3074, 480, 7218, 512, 3947, 596, 4400, 311, 3371, 0, 1283, 596, 1120, 1063, 7564, 358, 990, 449, 2268]

First 20 Decoded Tokens:  Monica Geller:
There's nothing to tell! He's just some guy I work with!




In [7]:
print(len(set(tokens)))

17976


In [9]:
17984%64

0

In [139]:
'gpt_model_weights_14M_CP%d.pth'%(5000//5000)

'gpt_model_weights_14M_CP1.pth'

In [10]:
with open('Datasets/processed_data/friends/friends.txt', 'r', encoding='utf-8') as f:
    text = f.read()

# here are all the unique characters that occur in this text
chars = sorted(list(set(text)))
vocab_size = len(chars)
# create a mapping from characters to integers
stoi = { ch:i for i,ch in enumerate(chars) }
itos = { i:ch for i,ch in enumerate(chars) }
encode = lambda s: [stoi[c] for c in s] # encoder: take a string, output a list of integers
decode = lambda l: ''.join([itos[i] for i in l]) # decoder: take a list of integers, output a string


In [11]:
print(chars)

['\n', ' ', '!', '"', '#', '$', '%', '&', "'", '(', ')', '*', '+', ',', '-', '.', '/', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '>', '?', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '[', '_', '`', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '{', '}']


# Hyperparameters

In [4]:

# batch_size = 128 # independent batches of sequencial text that are gonna process in parallel
# block_size = 2048 # maximum context length of input sequence for predictions
# max_iters = 50000 # total training loops
# eval_interval = 500 # for evaluating the model periodically
# learning_rate = 3e-4 # 
# device = 'cuda' if torch.cuda.is_available() else 'cpu' # cuda will be used for training on GPU
# eval_iters = 200
# n_embd = 256 #size of the embedding layer
# n_head = 16 # no.of self attention heads
# n_layer = 16 # no.of hidden layers
# dropout = 0.2 # dropout layers to avoid overfitting the model
# vocab_size = len(set(tokens)) # no.of individual tokens


# Transformer Model Architecture

In [15]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.nn import TransformerEncoder, TransformerEncoderLayer

In [174]:
# Train and Test splits
data = torch.tensor([i for i in range(1,101)], dtype=torch.long)
n = int(0.85*len(data)) # first 85% will be train and rest for validation
train_data = data[:n]
val_data = data[n:]

BATCH_INDEX = 0

#
batch_size = 4 # independent batches of sequencial text that are gonna process in parallel
block_size = 8 

# data loading
def get_batch(split):
    global BATCH_INDEX
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.tensor([i for i in range(BATCH_INDEX, BATCH_INDEX+(batch_size*block_size), block_size)])
    print(ix)
    #block_list = [data[i:i+block_size] for i in ix]
    block_list = data[ix[0]:ix[-1]+block_size +1 ]
    x =[]
    if len(block_list) < batch_size*block_size:
        block_list = torch.cat( (block_list, torch.zeros( batch_size*block_size - len(block_list)+1 )), 0 )
        #x = torch.stack(block_list)
        x = torch.reshape(block_list[:-1],(batch_size,block_size))        
    else:
        #x = torch.stack(block_list)
        x = torch.reshape(block_list[:-1],(batch_size,block_size)) 
        
    #x = torch.reshape(block_list,(batch_size,block_size))
    print("x: ",x)
    
    y = torch.reshape(block_list[1:],(batch_size,block_size)) 
    print("y: ",y)
    
    
    BATCH_INDEX+= batch_size*block_size
    

In [155]:
x = [1,2,3,4,5,6,7,8,9]
# x[:-1] # except last
x[1:] # except first

[2, 3, 4, 5, 6, 7, 8, 9]

In [167]:
enc.encode(" ")

[220]

In [156]:
torch.cat( (torch.tensor([1 for i in range(4)])[:2], torch.zeros( 4*8 - 31)),0 )

tensor([1., 1., 0.])

In [157]:
a = torch.tensor([i for i in range(4)])
#a.view(2, 2)
torch.reshape(a, (2, 2))
# b = torch.tensor([[0, 1], [2, 3]])
# torch.reshape(b, (-1,))
torch.zeros(5)
#torch.cat(a,  )

tensor([0., 0., 0., 0., 0.])

In [165]:
torch.zeros(5)+220

tensor([220., 220., 220., 220., 220.])

In [158]:
get_batch('train')

tensor([ 0,  8, 16, 24])
x:  tensor([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29, 30, 31, 32]])
y:  tensor([[ 2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30, 31, 32, 33]])


In [159]:
get_batch('train')

tensor([32, 40, 48, 56])
x:  tensor([[33, 34, 35, 36, 37, 38, 39, 40],
        [41, 42, 43, 44, 45, 46, 47, 48],
        [49, 50, 51, 52, 53, 54, 55, 56],
        [57, 58, 59, 60, 61, 62, 63, 64]])
y:  tensor([[34, 35, 36, 37, 38, 39, 40, 41],
        [42, 43, 44, 45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54, 55, 56, 57],
        [58, 59, 60, 61, 62, 63, 64, 65]])


In [160]:
get_batch('train')

tensor([64, 72, 80, 88])
x:  tensor([[65., 66., 67., 68., 69., 70., 71., 72.],
        [73., 74., 75., 76., 77., 78., 79., 80.],
        [81., 82., 83., 84., 85.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])
y:  tensor([[66., 67., 68., 69., 70., 71., 72., 73.],
        [74., 75., 76., 77., 78., 79., 80., 81.],
        [82., 83., 84., 85.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])


In [6]:
# Train and Test splits
data = torch.tensor(tokens, dtype=torch.long)
n = int(0.85*len(data)) # first 85% will be train and rest for validation
train_data = data[:n]
val_data = data[n:]

BATCH_INDEX = 0

# data loading
def get_batch(split):
    global BATCH_INDEX
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data    
    ix = torch.tensor([i for i in range(BATCH_INDEX, BATCH_INDEX+(batch_size*block_size), block_size)])  
    # this mechanism allows model to predict next token
    # X tensor
    x = torch.stack([data[i:i+block_size] for i in ix])
    # y tensor
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])    
    x, y = x.to(device), y.to(device)
    BATCH_INDEX += block_size*batch_size
    return x, y

In [26]:
@torch.no_grad()
def estimate_loss():
    out = {}
    model.eval()
    for split in ['train', 'val']:
        losses = torch.zeros(eval_iters)
        for k in range(eval_iters):
            X, Y = get_batch(split)
            logits, loss = model(X, Y)
            losses[k] = loss.item()
        out[split] = losses.mean()
    model.train()
    return out

# NLM architectue

In [167]:
# Single Self-attention head from the transformers
class Head(nn.Module):
   
    def __init__(self, head_size):
        super().__init__()
        self.key = nn.Linear(n_embd, head_size, bias=False)
        self.query = nn.Linear(n_embd, head_size, bias=False)
        self.value = nn.Linear(n_embd, head_size, bias=False)
        self.register_buffer('tril', torch.tril(torch.ones(block_size, block_size)))
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        # input of size (batch, time-step, channels)
        # output of size (batch, time-step, head size)
        B,T,C = x.shape
        k = self.key(x)   # (B,T,hs)
        q = self.query(x) # (B,T,hs)
        # compute attention scores ("affinities")
        wei = q @ k.transpose(-2,-1) * k.shape[-1]**-0.5 # (B, T, hs) @ (B, hs, T) -> (B, T, T)
        wei = wei.masked_fill(self.tril[:T, :T] == 0, float('-inf')) # (B, T, T)
        wei = F.softmax(wei, dim=-1) # (B, T, T)
        wei = self.dropout(wei)
        # perform the weighted aggregation of the values
        v = self.value(x) # (B,T,hs)
        out = wei @ v # (B, T, T) @ (B, T, hs) -> (B, T, hs)
        return out

class MultiHeadAttention(nn.Module):
    """ multiple heads of self-attention in parallel """

    def __init__(self, num_heads, head_size):
        super().__init__()
        self.heads = nn.ModuleList([Head(head_size) for _ in range(num_heads)])
        self.proj = nn.Linear(head_size * num_heads, n_embd)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        out = torch.cat([h(x) for h in self.heads], dim=-1)
        out = self.dropout(self.proj(out))
        return out

class FeedFoward(nn.Module):
    """ a simple linear layer followed by a non-linearity """

    def __init__(self, n_embd):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(n_embd, 4 * n_embd),
            nn.ReLU(),
            nn.Linear(4 * n_embd, n_embd),
            nn.Dropout(dropout),
        )

    def forward(self, x):
        return self.net(x)

class Block(nn.Module):
    """ Transformer block: communication followed by computation """

    def __init__(self, n_embd, n_head):
        # n_embd: embedding dimension, n_head: the number of heads we'd like
        super().__init__()
        head_size = n_embd // n_head
        self.sa = MultiHeadAttention(n_head, head_size)
        self.ffwd = FeedFoward(n_embd)
        self.ln1 = nn.LayerNorm(n_embd)
        self.ln2 = nn.LayerNorm(n_embd)

    def forward(self, x):
        x = x + self.sa(self.ln1(x))
        x = x + self.ffwd(self.ln2(x))
        return x

class GPTLanguageModel(nn.Module):
    
    def __init__(self):
        super().__init__()        
        self.token_embedding_table = nn.Embedding(vocab_size, n_embd)
        self.position_embedding_table = nn.Embedding(block_size, n_embd)
        self.blocks = nn.Sequential(*[Block(n_embd, n_head=n_head) for _ in range(n_layer)])
        self.ln_f = nn.LayerNorm(n_embd) # final layer norm
        self.lm_head = nn.Linear(n_embd, vocab_size)

        # better init, not covered in the original GPT video, but important, will cover in followup video
        #self.apply(self._init_weights)

    def _init_weights(self, module):
        if isinstance(module, nn.Linear):
            torch.nn.init.normal_(module.weight, mean=0.0, std=0.02)
            if module.bias is not None:
                torch.nn.init.zeros_(module.bias)
        elif isinstance(module, nn.Embedding):
            torch.nn.init.normal_(module.weight, mean=0.0, std=0.02)


    def forward(self, idx, targets=None):
        B, T = idx.shape

        idx = idx.clamp(0, vocab_size - 1)  
        tok_emb = self.token_embedding_table(idx) 
        pos_emb = self.position_embedding_table(torch.arange(T, device=device)) # (T,C)
        x = tok_emb + pos_emb
        x = self.blocks(x) 
        x = self.ln_f(x) 
        logits = self.lm_head(x) 

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            # Clip the targets tensor to the valid range
            targets = targets.clamp(0, vocab_size - 1)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):        
        for _ in range(max_new_tokens):
            idx_cond = idx[:, -block_size:]            
            logits, loss = self(idx_cond)
            logits = logits[:, -1, :] 
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)            
            idx_next = torch.multinomial(probs, num_samples=1)         
            idx = torch.cat((idx, idx_next), dim=1)
        return idx

In [176]:
# Configuring Hyper-parameters

batch_size = 64 # independent batches of sequencial text that are gonna process in parallel
block_size = 512 # maximum context length of input sequence for predictions
max_iters = 5000 # total training loops
eval_interval = 500 # for evaluating the model periodically
learning_rate = 3e-4 # 
device = 'cuda' if torch.cuda.is_available() else 'cpu' # cuda will be used for training on GPU
eval_iters = 200
n_embd = 256 #size of the embedding layer
n_head = 6 # no.of self attention heads
n_layer = 4 # no.of hidden layers
dropout = 0.2 # dropout layers to avoid overfitting the model
vocab_size = 5864 #len(set(tokens)) # no.of individual tokens

#
baseModel = GPTLanguageModel()

In [177]:
# Loading pre-trained weights with 6.2 million parameters
baseModel.load_state_dict(torch.load('gpt_model_weights_6_2_M.pth', map_location=torch.device('cpu')))

<All keys matched successfully>

In [179]:
# Text Generation

context = torch.tensor([enc.encode("How you doing")], dtype=torch.long, device='cpu')

print(enc.decode(baseModel.generate(context, max_new_tokens=64)[0].tolist()).replace("inder",""), end="")

How you doing? I've went there too much way was here too. I was I'm Mich. What do. fil,. We have ever.... I think we do it'd have ever. I mean,... at the... ,a $7.

In [180]:
# Configuring Hyper-parameters for 10 million parameter model

batch_size = 64 # independent batches of sequencial text that are gonna process in parallel
block_size = 512 # maximum context length of input sequence for predictions
max_iters = 500 # total training loops
eval_interval = 500 # for evaluating the model periodically
learning_rate = 3e-4 # 
device = 'cuda' if torch.cuda.is_available() else 'cpu' # cuda will be used for training on GPU
eval_iters = 200
n_embd = 324 #size of the embedding layer
n_head = 6 # no.of self attention heads
n_layer = 5 # no.of hidden layers
dropout = 0.2 # dropout layers to avoid overfitting the model


In [181]:
baseModel10 = GPTLanguageModel()

In [182]:
baseModel10.load_state_dict(torch.load('gpt_model_weights_10M.pth', map_location=torch.device('cpu')))

<All keys matched successfully>

In [183]:
context = torch.tensor([enc.encode("Hi")], dtype=torch.long, device='cpu')
print(enc.decode(baseModel10.generate(context, max_new_tokens=128)[0].tolist()).replace("inder",""), end="")

Hi.? What almost you never other.? You and play I,, don't d' l? .., no no. th, it's, like, ok, it's., see, where are you know that's good, y', wait...? I mean, about theless rem74. it was. It's 'cause we thing. That is so great. We won't. We're never get off with you something. That's like this was a you know who doesn't youruff, my place

# NLM  ASCII 

# NLM 88M

In [163]:
import tiktoken
import time
import torch

In [164]:
enc = tiktoken.get_encoding("cl100k_base")

In [165]:
# hyperparameters
batch_size = 24 # how many independent sequences will we process in parallel?
block_size = 256 # what is the maximum context length for predictions?
max_iters = 50000
eval_interval = 500
learning_rate = 3e-4
device = 'cuda' if torch.cuda.is_available() else 'cpu'
eval_iters = 200
n_embd = 384
n_head = 6
n_layer = 6
dropout = 0.2
vocab_size = enc.n_vocab

In [166]:
baseModel88M = GPTLanguageModel()

In [174]:
# baseModel88M.load_state_dict(torch.load('/Users/krishna/Downloads/gpt_model_weights_88M_CP4_bnr.pth',
#                                        map_location=torch.device('mps')))
baseModel88M.load_state_dict(torch.load('/Users/krishna/Documents/UTA/Capstone/outputs/88M_friends/gpt_model_weights_88M_CP30_rk22.pth',
                                       map_location=torch.device('mps')))

# baseModel88M.load_state_dict(torch.load('/Users/krishna/Documents/UTA/Capstone/outputs/88M_friends/gpt_model_weights_88M_CP55_rk22.pth',
#                                         map_location=torch.device('mps')))

<All keys matched successfully>

In [179]:
context = torch.tensor([enc.encode("Ross: hey Joey do you wanna go out")], dtype=torch.long, device=torch.device('cpu'))
print(enc.decode(baseModel88M.generate(context, max_new_tokens=512)[0].tolist()), end="")

Ross: hey Joey do you wanna go out with your fine.

Monica Geller:
Oh, my god, I'm just ate it, "Where are you?

Ross Geller:
No! No, I'm, no no way learn for a class I'm in again."

Monica Geller:
Excuse me?

Joey Tribbiani:
Great! Well hey, I'm here to meet you.

Chandler Bing:
Oh that's funny, hi. Yeah.

Ross Geller:
Hi!

Phoebe Buffay:
Oh you are so fine, please. I was fine, umm, and try the best goodnight from Aunt Single card in this craving for a lot.

Phoebe Buffay:
He's lace.

Ross Geller:
He's hair.

Phoebe Buffay:
Oh yeah. So what's up. What is it is great. Can I get up?

Joey Tribbiani:
He's gone. You remembered porn if we had plans to ride along with you in personal stuff, discussed... make. So you seen me?

Phoebe Buffay:
Well, maybe I should just set up town.

Joey Tribbiani:
All right, bye.

Phoebe Buffay:
Oh that's dead but, don't he wants to hear you, there's going in on that's taking it?

Joey Tribbiani:
Well, maybe he's never going him.

Phoebe Buffay:
Well, actuall